apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: bookinfo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ratings
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
