replicaCount: 1

image:
  repository: registry.sol.lab:5443/bookinfo/reviews
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

labels:
  solOwner: "hansol"
