apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: details  
  namespace: argocd
spec:
  project: bookinfo
  source:
    repoURL: 'https://gitlab.sol.lab:8443/bookinfo-k8s/details.git'
    targetRevision: main
    path: helm/details
    helm:
      releaseName: details  # 고정
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bookinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
