---
apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: bookinfo
spec:
  type: ClusterIP
  selector:
    app: details
  ports:
    - protocol: TCP
      port: 9080       # 서비스 내부 포트
      targetPort: 9080 # 컨테이너의 포트