# 50% 확률로 503 Service Unavailable 반환
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ratings-faulty
  namespace: bookinfo
spec:
  hosts:
  - ratings
  http:
  - route:
    - destination:
        host: ratings
        subset: success
    fault:
      abort:
        percentage:
          value: 50.0
        httpStatus: 503

---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: ratings-faulty
  namespace: bookinfo
spec:
  host: ratings
  subsets: # subset 정의
    - labels:               
        version: v1        
      name: success                 