---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: canary-details   # 단지 virtual service의 이름 k8s service와 관련x
  namespace: bookinfo
spec:
  hosts:
    - details     # 라우팅 규칙을 적용할 k8s service DNS이름
  http:
    - route:
        - destination:
            host: details # Target이 되는 k8s service DNS이름
            subset: internal # 외부 정보 사용               
          weight: 30
        - destination:
            host: details # Target이 되는 라우팅 규칙을 적용할 k8s service DNS이름
            subset: external # 외부 정보 사용               
          weight: 70 # google api 사용

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: canary-details
  namespace: bookinfo
spec:
  host: details
  subsets: # subset 정의
    - labels:               
        version: v1        
      name: internal             
    - labels:                
        version: v2       
      name: external           