apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -v0
resources:
  - ./yaml/deployment.yaml
  - ./yaml/service.yaml

images:
  - name: registry.sol.lab:5443/bookinfo/productpage
    newTag: v0  

patches:
  - target:
      kind: Deployment
      name: productpage
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1  
      - op: add
        path: /spec/template/metadata/labels/version
        value: v0
      - op: add
        path: /spec/selector/matchLabels/version
        value: v0
      - op: replace
        path: /metadata/name
        value: details-v0
