replicaCount: 1

image:
  repository: registry.sol.lab:5443/bookinfo/productpage
  tag: v0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

labels:
  solOwner: "hansol"

istio:
  enabled: true

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20

productpageConfig:
  FLOOD_FACTOR: "0"