---
- name: create k8s monitoring
  shell: "../files/k8s_monitoring/create_lb.sh"
  environment:
    PATH : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
    KUBECONFIG: "{{kube_config}}"  
  register: installing
  when: '"{{k8s_service_type}}" == "loadbalancer"'

- debug: var=installing

- name: create k8s monitoring
  shell: "../files/k8s_monitoring/create_nodeport.sh"
  environment:
    PATH : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
    KUBECONFIG: "{{kube_config}}"  
  register: installing
  when: '"{{k8s_service_type}}" == "nodeport"'
- debug: var=installing