apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-{{ .Values.image.tag }}
  namespace: bookinfo
  labels:
    sol.io/owner: "{{ .Values.labels.solOwner }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: productpage
      version: "{{ .Values.image.tag }}"
  template:
    metadata:
      labels:
        app: productpage
        sol.io/owner: "{{ .Values.labels.solOwner }}"
        {{- if .Values.istio.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
        version: "{{ .Values.image.tag }}"
    spec:
      containers:
        - name: productpage-{{ .Values.image.tag }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
