apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-{{ .Values.image.tag }}
  namespace: bookinfo
  labels:
    sol.io/owner: "{{ .Values.labels.solOwner }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
        sol.io/owner: "{{ .Values.labels.solOwner }}"
    spec:
      containers:
        - name: reviews-{{ .Values.image.tag }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
