apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  namespace: bookinfo
  labels:
    sol.io/owner: "hansol" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
        sol.io/owner: "hansol" 
    spec:
      containers:
        - name: reviews
          image: registry.sol.lab:5443/bookinfo/reviews:v1
          ports:
            - containerPort: 9080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"


