--- 
############### join nfs into cloud service nas
- name: create ssl directory
  file:
    path: "{{nas_mount_path}}"
    state: directory

- name: Mount an NFS volume
  mount:
    src: "{{nfs_path}}"
    path: "{{nas_mount_path}}"
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
    state: mounted
    fstype: nfs4

- name: Register NFS mount in /etc/fstab
  blockinfile:
    path: /etc/fstab
    line: "{{ nfs_path }} {{ nas_mount_path }} nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 0 0"
    create: yes

