# Kubernetes에서 실행 중인 모든 Pod와 Namespace의 정보를 수집
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: fluentd-fluentd-elasticsearch
  labels:
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/version: 0.1.0
    app.kubernetes.io/component: log-forwarder
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-cluster-watch
  labels:
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/version: 0.1.0
    app.kubernetes.io/component: log-forwarder
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-fluentd-elasticsearch
  labels:
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/version: 0.1.0
    app.kubernetes.io/component: log-forwarder
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: fluentd-fluentd-elasticsearch
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: k8s-cluster-watch
  apiGroup: rbac.authorization.k8s.io

