---  
- name: Creating mattermost directory
  file:
    path: '{{item}}'
    state: directory
    mode: 0777
  loop:
    - '{{mattermost_dir}}'  
    - '{{mattermost_data_dir}}'
    - '{{mattermost_data_dir}}/config'
    - '{{mattermost_data_dir}}/data'
    - '{{mattermost_data_dir}}/logs'
    - '{{mattermost_data_dir}}/plugins'
    - '{{mattermost_data_dir}}/client/plugins'
    - '{{mattermost_data_dir}}/bleve-indexes'

- name: copy directory to the remote server
  copy:
    src: "../files/mattermost/"
    dest: "{{mattermost_dir}}"

- name : change owner mattermost data directory
  shell : chown -R 2000:2000 {{mattermost_data_dir}}

- name: insert variable
  set_fact:
    mattermost_ip: "{{infra_lb_domain}}"

- name: configure config sql output template
  template:
    src: "../templates/infra/mattermost.j2"
    dest: "{{mattermost_dir}}/.env"

- name : install mattermost using docker-compose
  shell : cd {{mattermost_dir}}; docker-compose  -f ./docker-compose.yml -f ./docker-compose.without-nginx.yml  up -d