apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./yaml/deployment.yaml
  - ./yaml/service.yaml

images:
  - name: registry.sol.lab:5443/bookinfo/details
    newTag: v0  

# 책 정보 외부 Google Books API를 통해 실제 책 정보를 가져오게 함
configMapGenerator:
  - name: details-config
    literals:
      - ENABLE_EXTERNAL_BOOK_SERVICE=false

patches:
  - target:
      kind: Deployment
      name: details
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1  
      - op: add
        path: /spec/template/metadata/labels/version
        value: v0
      - op: add
        path: /spec/selector/matchLabels/version
        value: v0
      - op: replace
        path: /metadata/name
        value: details-v0
