apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: v2-
resources:
  - ./yaml/deployment.yaml
  - ./yaml/service.yaml

images:
  - name: registry.sol.lab:5443/bookinfo/reviews
    newTag: v2  

patches:
  - target:
      kind: Deployment
      name: reviews
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1  
      - op: add
        path: /spec/template/metadata/labels/version
        value: v2
      - op: add
        path: /spec/selector/matchLabels/version
        value: v2
      - op: add
        path: /spec/template/metadata/annotations
        value:
          sidecar.istio.io/inject: "true"