---
- name: deploy aws cloud provider
  hosts: localhost
  become: yes
  connection: local
  serial: 1
  gather_facts: no  
  vars_files:
    - ./{{vars_file_name}}.yaml
  roles:
    - k8s_cloud_provider