cluster:
  name: kubernetes
hubble:
  enabled: [HUBBLE_ENABLE]
  metrics:
    enableOpenMetrics: [HUBBLE_OPEN_METRICS_ENABLE]
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
  relay:
    enabled: [HUBBLE_RELAY_ENABLE]
  ui:
    enabled: [HUBBLE_UI_ENABLE]
    service:
      type: [HUBBLE_UI_SVC_TYPE]
      nodePort: 31070
ipam:
  operator:
    clusterPoolIPv4MaskSize: [CILIUM_SUBNETMASK]
    clusterPoolIPv4PodCIDRList: [CILIUM_PODCIDR]
operator:
  prometheus:
    enabled: [CILIUM_OPERATOR_P8S_ENABLE]
  replicas: 1
prometheus:
  enabled: [CILIUM_P8S_ENABLE]
routingMode: tunnel
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnelProtocol: vxlan

